name: terradash-islands-db
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - geopandas>=1.0,<2
  - numpy>=2,<3
  - pyogrio>=0.9,<1
  - pyproj>=3.6,<4
  - rasterio>=1.4,<2
  - requests>=2.32,<3
  - shapely>=2.0,<3
  - pytest>=8,<9
